CREATE TABLE IF NOT EXISTS agent_workflows (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  conversation_id VARCHAR(128) NOT NULL,
  actor_user_id BIGINT UNSIGNED NOT NULL,
  workflow_id VARCHAR(64) NOT NULL,
  workflow_type VARCHAR(64) NOT NULL,
  workflow_state VARCHAR(32) NOT NULL,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  snapshot_schema_version SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  snapshot_json LONGTEXT NOT NULL,
  execution_status VARCHAR(32) NOT NULL DEFAULT 'idle',
  execution_token VARCHAR(64) NULL,
  execution_operation VARCHAR(64) NULL,
  business_key CHAR(64) NULL,
  request_id VARCHAR(64) NULL,
  execution_request_schema_version SMALLINT UNSIGNED NULL,
  execution_request_json LONGTEXT NULL,
  execution_result_schema_version SMALLINT UNSIGNED NULL,
  execution_result_json LONGTEXT NULL,
  write_effect VARCHAR(32) NULL,
  lease_expires_at DATETIME(3) NULL,
  expires_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_agent_workflow_key (
    tenant_id,
    conversation_id,
    actor_user_id
  ),
  KEY idx_agent_workflow_expiry (expires_at),
  KEY idx_agent_workflow_recovery (execution_status, lease_expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
