# ⚠️ 请替换为实际的钉钉群机器人 Webhook 地址和密钥
targets:
  ops:
    url: https://oapi.dingtalk.com/robot/send?access_token=e17ec748de421f45395e623da8b23cd762834de1e1b90bce9a02ebfd6010fe7d
    secret: SEC2dceaf20f33052045188f391d2a66c4a5dd5747c30d329e2b81e3c9af3b9ad6a
    message:
      title: '{{ template "ding.link.title" . }}'
      text: '{{ template "ding.link.content" . }}'
