name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: make ci-test

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          args: --timeout=5m --new-from-rev=origin/master

      - name: Build application
        run: make ci-build

      - name: Build Docker image
        run: make docker-build-prod
